#!/usr/bin/env bash
# Install and build the pinned simulator in this checkout, without system changes.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [[ ${1:-} != "" && ${1:-} != "--skip-sync" ]]; then
  echo "Usage: bash scripts/bootstrap_minecraft.sh [--skip-sync]" >&2
  exit 2
fi

# On NixOS, pip wheels and Minecraft's native libraries need explicit library paths.
# The shell uses the user's configured nixpkgs; no machine configuration is modified.
if [[ -e /etc/NIXOS && ${MCSOCIETY_NATIVE_SHELL:-0} != 1 ]]; then
  export MCSOCIETY_BOOTSTRAP_SKIP_SYNC=${1:-}
  exec nix-shell -E '
    with import <nixpkgs> {};
    mkShell {
      packages = [ jdk21 cmake gcc glew libGL libpng pkg-config ];
      LD_LIBRARY_PATH = lib.makeLibraryPath [
        stdenv.cc.cc zlib libGL glfw openal libpulseaudio
        libx11 libxext libxrandr libxcursor libxi libxxf86vm
      ];
    }
  ' --run 'MCSOCIETY_NATIVE_SHELL=1 bash scripts/bootstrap_minecraft.sh ${MCSOCIETY_BOOTSTRAP_SKIP_SYNC:-}'
fi

if [[ ${1:-} != --skip-sync ]]; then
  uv sync --extra minecraft
fi
python=.venv/bin/python
[[ -x "$python" ]] || { echo "Create .venv with uv sync --extra minecraft first." >&2; exit 1; }

if [[ -z ${JAVA_HOME:-} ]]; then
  JAVA_HOME=$("$python" -c 'import pathlib, shutil; print(pathlib.Path(shutil.which("javac") or "javac").resolve().parents[1])')
fi
# Nix packages expose bin/include symlinks above the actual JDK directory.
if [[ -d "$JAVA_HOME/lib/openjdk" ]]; then JAVA_HOME="$JAVA_HOME/lib/openjdk"; fi
export JAVA_HOME
"$JAVA_HOME/bin/java" -version 2>&1 | head -1 | grep -q '"21\.' || {
  echo "JAVA_HOME must select JDK 21 (including JNI headers)." >&2; exit 1;
}
command -v cmake >/dev/null
command -v c++ >/dev/null
export GRADLE_USER_HOME="$PWD/.runtime/gradle"
export MCSOCIETY_MINECRAFT_PATH="$PWD/.runtime/minecraft"
export PATH="$JAVA_HOME/bin:$PATH"
if [[ -d /run/opengl-driver/lib ]]; then
  export LD_LIBRARY_PATH="/run/opengl-driver/lib:${LD_LIBRARY_PATH:-}"
fi

"$python" - <<'PY'
import importlib.metadata
import importlib.resources
from pathlib import Path
import shutil

runtime = Path('.runtime/minecraft')
source = Path(str(importlib.resources.files('craftground_runtime_mc121')))
version = importlib.metadata.version('craftground-runtime-mc121')
marker = runtime / '.mcsociety-runtime-version'
if runtime.exists() and marker.exists() and marker.read_text().strip() != version:
    raise SystemExit('Runtime version changed. Remove .runtime/minecraft and rerun bootstrap.')
if not runtime.exists():
    shutil.copytree(source, runtime, ignore=shutil.ignore_patterns('__pycache__', '*.pyc'))
(runtime / 'gradlew').chmod(0o755)
marker.write_text(version + '\n')
print(f'CraftGround {importlib.metadata.version("craftground")}; MC 1.21 runtime {version}')
PY

"$python" scripts/patch_runtime.py "$MCSOCIETY_MINECRAFT_PATH"
"$MCSOCIETY_MINECRAFT_PATH/gradlew" -p "$MCSOCIETY_MINECRAFT_PATH" --no-daemon build

# Quote values for safe sourcing, including paths containing spaces.
{
  printf '# Generated by scripts/bootstrap_minecraft.sh\n'
  for name in JAVA_HOME GRADLE_USER_HOME MCSOCIETY_MINECRAFT_PATH PATH LD_LIBRARY_PATH NIX_CFLAGS_COMPILE NIX_LDFLAGS; do
    printf 'export %s=%q\n' "$name" "${!name:-}"
  done
} > .runtime/env.sh
echo "Built Minecraft runtime. Run: source .runtime/env.sh"
echo "Then: .venv/bin/python scripts/smoke_raw.py"
